name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: ifeds-oau
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, curl, gd, fileinfo, exif, soap, bcmath, sodium, opcache
        coverage: none

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Composer dependencies
      run: |
        composer install --no-dev --optimize-autoloader --no-interaction

    - name: Install NPM dependencies
      run: |
        npm ci

    - name: Build assets
      run: |
        npm run build

    - name: Generate application key
      run: |
        php artisan key:generate --force

    - name: Cache configuration
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Set proper permissions
      run: |
        chmod -R 755 storage/
        chmod -R 755 bootstrap/cache/

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Post-deployment setup
      run: |
        echo "Deployment completed successfully!"
        echo "Your application is now live at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
